apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dotnet-scratch
  name: dotnet-scratch
  namespace: default
spec:
  containers:
  - command: 
    - sh
    args:
    - -c
    - "sleep 1000000"
    image: mcr.microsoft.com/dotnet/sdk:5.0
    imagePullPolicy: Always
    name: dotnet-scratch
    resources:
      limits:
        memory: "3Gi"
        cpu: "0.25"
    env:
    - name: COMPlus_gcAllowVeryLargeObjects
      value: "1"
    - name: DOTNET_gcAllowVeryLargeObjects
      value: "1"
  restartPolicy: Never 
